import React from "react";


export default function PrivacyPolicyPopup({ onClose }) { // Added onClose prop for practical use
  return (
    // Full screen overlay: fixed, centered, dark backdrop
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
        
        {/* The Responsive Card Container */}
        <div 
            className="bg-white rounded-lg shadow-2xl w-full max-w-3xl p-6 md:p-8 
                       max-h-[90vh] overflow-y-auto relative space-y-4" // Key classes for responsive card
        >
            
            {/* Optional Close Button */}
            {onClose && (
              <button
                onClick={onClose}
                className="absolute top-4 right-4 text-gray-500 hover:text-gray-800 transition-colors"
                aria-label="Close"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            )}

            <h1 className="text-3xl font-bold">Privacy Policy</h1>
            <p className="text-sm text-gray-500">Effective date: November 17, 2025</p>
            <div className="h-0.5 bg-gray-100 my-4"></div> {/* Separator */}

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">1. Introduction</h2>
              <p>
                ClariCase ("we", "our", "us") provides an AI-powered platform that helps
                users summarize, organize, and understand information related to civil
                cases (the "Service"). This Privacy Policy explains how we collect, use,
                disclose, and protect personal information when you use our Service.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">2. Information We Collect</h2>
              <p>
                <strong>a. Information you provide:</strong> account registration details
                (name, email, password), case files and documents you upload, messages,
                support requests, billing information (when applicable).
              </p>
              <p>
                <strong>b. Automatically collected information:</strong> usage data (pages
                visited, features used), device and browser information, IP address,
                cookies and similar technologies, crash logs and performance metrics.
              </p>
              <p>
                <strong>c. Derived or inferred data:</strong> summaries, tags, or metadata
                generated by the Service from your uploaded content.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">3. How We Use Your Information</h2>
              <p>
                We use information to provide, maintain, and improve the Service, to
                process payments, for account administration, to communicate with you, to
                personalize and enhance features, and to meet legal and compliance
                obligations.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">4. Legal Bases for Processing</h2>
              <p>
                Where applicable, we rely on: your consent, performance of a contract, our
                legitimate interests (service improvement, fraud detection), and
                compliance with legal obligations.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">5. Sharing & Disclosure</h2>
              <p>
                We may share information with service providers (hosting, analytics,
                payment processors), professional advisors, law enforcement when required
                by law, and in connection with a business transaction. We do not sell
                personal information for advertising purposes.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">6. Third-Party Services</h2>
              <p>
                We use third-party processors such as cloud providers and analytics tools.
                We require them to process data only as instructed.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">7. Data Retention</h2>
              <p>
                We retain personal information as long as necessary to provide the
                Service and for legitimate business purposes like backups, fraud
                prevention, and compliance.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">8. Your Rights</h2>
              <p>
                Depending on jurisdiction, you may have rights to access, correct, delete,
                or export your personal data; restrict or object to processing; and
                withdraw consent.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">9. Security</h2>
              <p>
                We implement administrative, technical, and physical safeguards to protect
                personal information.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">10. Children</h2>
              <p>
                Our Service is not directed to children under 16, and we do not knowingly
                collect information from children.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">11. International Transfers</h2>
              <p>
                We may transfer data across borders and rely on safeguards like
                contractual protections.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">12. Cookies & Tracking</h2>
              <p>
                We use cookies and similar technologies. You may control cookies via your
                browser settings.
              </p>
            </section>

            <section className="space-y-2">
              <h2 className="text-xl font-semibold">13. Updates to This Policy</h2>
              <p>
                We may modify this Privacy Policy and update the "Last updated" date.
              </p>
            </section>

            <section className="space-y-2 pb-6">
              <h2 className="text-xl font-semibold">14. Contact</h2>
              <p>
                For questions, contact us at <strong>team@claricase.xyz</strong>.
              </p>
            </section>
        </div>
    </div>
  );
}